all: eight_divisors

eight_divisors: eight_divisors.cc
	g++ $^ -std=c++11 -lprimesieve -o $@

.PHONY: clean

clean:
	rm -rf coin
	rm -rf largest_exponential
	rm -rf path_sum_two_ways
	rm -rf singular_integer_right_triangles
	rm -rf path_sum_three_ways  
	rm -rf counting_rectangles
	rm -rf arranged_probability
	rm -rf the_incenter_of_a_triangle
	rm -rf bouncy_numbers
	rm -rf concealed_square
	rm -rf eight_divisors
